### ISSUE TITLE
Unhandled Exception: Exception: Unsupported Font: Roboto

### ISSUE THREAD

**Issue by EmreSURK** [joseph-grabinger/flutter_to_pdf#56]
Thanks for the awesome package. 

Why does the package seek for Robot? I am on Android but not using Robot.

How can we pick a supported font? Is it possible in Export Options? 

Thanks.

**Comment by joseph-grabinger** [comment]
Hey, thanks for the feedback! 

Currently the package only supports the following `ExportOptions` :

- `textFieldOptions`
- `checkboxOptions`
- `pageFormatOptions`

Meaning only the style/decoration of TextFields  and Checkboxes can be overridden. This can be used if one desires to have these widgets in a different style in the exported PDF than in the app.

For `Text` widgets the `TextStyle` is also applied to the corresponding PDF element. If you set the `fontFamily` property of a `Text` widget's  `style` property to  Courier, Helvetica, Times, ZapfDingbats, or Symbol, the text element in the PDF will have said font. 

There is already a feature request for custom font support https://github.com/joseph-grabinger/flutter_to_pdf/issues/46.

Regarding the `Unhandled Exception: Unsupported Font: Roboto` I would need a little more insight, e.g. a minimal reproduction of the bug and maybe also your `flutter doctor -v` output  since I wasn't able to reproduce the issue on Android when setting the fontFamily in the example.

If you are looking for additional `ExportOptions` for `Text` widgets, feel free to open a feature request for it :)
