### ISSUE TITLE
Unsupported Text Style, Font family, Shape Decoration

### ISSUE THREAD

**Issue by mainulislamfahim** [joseph-grabinger/flutter_to_pdf#63]
I used Text Widget where normally I used Text Style for underline when I used this plugin it tells Unsupported 
Unsupported TextAlign: TextAlign.start; defaulting to null
I/flutter (12707): Unsupported FontWeight: FontWeight.w600; defaulting to FontWeight.normal
I/flutter (12707): Unsupported TextDecorationStyle: TextDecorationStyle.dotted; defaulting to TextDecorationStyle.solid
I/flutter (12707): Unsupported TextAlign: TextAlign.start; defaulting to null
I/flutter (12707): Unsupported TextAlign: TextAlign.start; defaulting to null
I/flutter (12707): Unsupported FontWeight: FontWeight.w600; defaulting to FontWeight.normal
I/flutter (12707): Unsupported TextDecorationStyle: TextDecorationStyle.dotted; defaulting to TextDecorationStyle.solid
I/flutter (12707): Unsupported TextAlign: TextAlign.start; defaulting to null
I/flutter (12707): Unsupported TextAlign: TextAlign.start; defaulting to null
.... and so on

**Comment by joseph-grabinger** [comment]
This is due to limitations from the [pdf](https://pub.dev/packages/pdf) package.

For `FontWeight`:

- only `FontWeight.normal` & `FontWeight.bold` are supported

For `TextDecorationStyle`:

- only `TextDecorationStyle.solid` & `TextDecorationStyle.double` are supported

But I saw that `TextAlign.start` and `TextAlign.end` are now supported.
Thus, #64 will add this functionality and this issue will be closed.

For further feature requests please open separate issues for each feature.
